---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    
verifier:
  name: testinfra
  lint:
    name: flake8
    
scenario:
  name: default

